# In docker-compose.yml (on the TEST device)
services:
  vector:
    image: timberio/vector:latest-alpine
    container_name: vector
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
      - ./test_logs/:/var/log/testdata/:ro
